# Generated by Django 3.1.7 on 2021-03-01 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 1, 26, 17, 493664), verbose_name='date published'),
        ),
    ]
