# Generated by Django 3.1.7 on 2021-03-03 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210303_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 23, 50, 31, 45470), verbose_name='date published'),
        ),
    ]
